site_name: Practica3.5 - Desplegar una app Flask

nav:  
  - Home: https://yahyalimouni.github.io
  - Practica2.1: https://yahyalimouni.github.io/practica2/
  - Practica2.2: https://yahyalimouni.github.io/practica2.2/
  - Practica2.3: https://yahyalimouni.github.io/practica2.3/
  - Practica2.4: https://yahyalimouni.github.io/practica2.4/
  - Practica2.5: https://yahyalimouni.github.io/practica2.5/
  - Practica2.6: https://yahyalimouni.github.io/practica2.6/
  - Practica3.3.4: https://yahyalimouni.github.io/practica3.4/
  - Practica3.5: https://yahyalimouni.github.io/practica3.5/
  - Practica-amp: https://yahyalimouni.github.io/practica-ampliacion/


theme:
  name: material  
  features:
    - navigation.tabs  
    - navigation.top  
    - search.highlight  
    - search.share  
    - navigation.tracking  


  palette:
    scheme: slate
    primary: cyan
    accent: indigo
